[package]
name = "mirl_windowing_minifb"
version = "0.0.0-alpha"
edition = "2024"
repository.workspace = true
license.workspace = true
authors.workspace = true

[features]
all = [
    "mirl_buffer/all",
    "mirl_extensions/all",
    "mirl_input/all",
    "mirl_system/all",
    "mirl_windowing_core/all",
]
_checking = [
    "mirl_buffer/_checking",
    "mirl_extensions/_checking",
    "mirl_input/_checking",
    "mirl_system/_checking",
    "mirl_windowing_core/_checking",
]
c_compatible = [
    "mirl_buffer/c_compatible",
    "mirl_extensions/c_compatible",
    "mirl_input/c_compatible",
    "mirl_system/c_compatible",
    "mirl_windowing_core/c_compatible",
]
cursor_show_hotspot = ["mirl_input/cursor_show_hotspot", "mirl_windowing_core/cursor_show_hotspot"]

[dependencies]
# MiniFB
minifb = { "version" = "0.28" }
mirl_buffer = { version = "0.0.0-alpha" }
mirl_extensions = { version = "0.0.0-alpha" }
mirl_input = { version = "0.0.0-alpha" }
mirl_system = { version = "0.0.0-alpha" }
mirl_windowing_core = { version = "0.0.0-alpha" }
raw-window-handle = { version = "0.6", default-features = false }

[build-dependencies]
mirl_build_tools = { workspace = true }

[lints]
workspace = true
